sudo: false
language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36

install:
    - pip install tox

script:
    - tox

branches:
  only:
    - master
  except:
    - sub-branch

notifications:
  email: false
