sudo: false
language: python

python:
  - "2.7"
  - "3.6"

env:
  matrix:
    - TOXENV=py27
    - TOXENV=py36

install:
    - pip install tox

script:
    - tox

branches:
  only:
    - master
  except:
    - sub-branch

notifications:
  email: false
